version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: georgegca/multi-language-al-folio:latest
    build: .
    ports:
      - 8080:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    command: jekyll serve --watch --port 4000 --host 0.0.0.0
